// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfqjxtuuqpllkvxhgirs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmcWp4dHV1cXBsbGt2eGhnaXJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NDYyNjMsImV4cCI6MjA3MTQyMjI2M30.N913Z2Bj1Yw5m-GigEQhTyl2gQJfTeL1u7YgkepRBSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});