// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrvjeifknhhuzfaactfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhydmplaWZrbmhodXpmYWFjdGZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODU4MzYsImV4cCI6MjA3MDA2MTgzNn0.P2xq2rBmlVvaX_Rp32xwugAR7DTqp1L_XkacYyKLg30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});